# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/StyleFusion',
                'doc_host': 'https://m0saan.github.io',
                'git_url': 'https://github.com/m0saan/StyleFusion',
                'lib_path': 'StyleFusion'},
  'syms': {'StyleFusion.core': {'StyleFusion.core.foo': ('core.html#foo', 'StyleFusion/core.py')}}}
